### ISSUE TITLE
plog has broken the windows builds

### ISSUE THREAD

**Issue by matthewware** [BBN-Q/libaps2#105]

**Comment by gribeill** [comment]
Any error message? AFAIK plog should work fine on windows but I am tempted to label this as "wontfix"

**Comment by matthewware** [comment]
Having that debate right now...  Check to appveyor log to see what I'm talking about.  It's some miscommunication with ostream.

**Comment by matthewware** [comment]
https://ci.appveyor.com/project/caryan/libaps2

**Comment by matthewware** [comment]
Now work under mingw.  Which is all we're going to support.
