### ISSUE TITLE
Matlab driver does not load under Linux 64 bit

### ISSUE THREAD

**Issue by bcdonovan** [BBN-Q/libaps2#27]
I can not load libaps2 into matlab on Linux MInt 17.1 64 bit with Matlab 2015a.

__int64 is not defined under linux and is causing errors [here](https://github.com/BBN-Q/libaps2/blob/a7f674f8a4a9b3389358da48ed68943570eb262a/src/matlab/libaps2.matlab.h#L68) and [here](https://github.com/BBN-Q/libaps2/blob/a7f674f8a4a9b3389358da48ed68943570eb262a/src/matlab/libaps2.matlab.h#L96-97).

Replacing __int64 with uint64 and libaps2.dll with libaps2.so gets me further but I run into a shared library issue from Matlab which I have not solved yet:

libstdc++.so.6: version 'GLIBCXX_3.4.19' not found as required by libaps2.so

**Comment by bcdonovan** [comment]
Matlab 2015a [supports](http://www.mathworks.com/support/compilers/R2015a/index.html?sec=glnxa64) gcc 4.7. The current asio library requires 4.8.

Changing the symbolic link that matlab uses to load libstdc++ is not the solution. Doing this causes matlab to crash.

**Comment by caryan** [comment]
I don't think it's asio that's the issue.  The ``this_thread::sleep_for`` is in our code.  For whatever reason though whenever something goes wrong in compiling it dumps a bunch of asio headers.

**Comment by caryan** [comment]
@bcdonovan  could you take a look and make sure the fix works for you.  

Also see [this post](http://choorucode.com/2015/02/26/how-to-switch-gcc-version-using-update-alternatives/) for a cleaner way to switch gcc versions that slaves g++ too.

**Comment by bcdonovan** [comment]
I can confirm that the fix/gcc-4.7-sleep_for branch let me compile a libaps.so which I could load into Matlab 2015a on linux. I still needed the fix/#27 branch to load the libaps2.so module into Matlab. 

I can now use the APS2 in waveform mode. 
+
Sequence mode is crashing with an error in the libhdf5.so which Matlab ships with, specifically in the H5check_version call.

**Comment by bcdonovan** [comment]
Crash when loading a HD5 file was caused by a HDF version check assert. Matlab generates and error stating that the HDF5 header files used to compile the application do not match the library version which the application is linked. It looks like Linux mint is shipping with libhdf5-7 version 1.8.11. Matlab has a library which is version 1.8.12 which is causing an assert to fail.

By setting the environment variable 

```
export HDF5_DISABLE_VERSION_CHECK=1
```

I was able to play a sequence file using Matlab 2015a under Linux.

**Comment by bcdonovan** [comment]
Linux Mint is based on Ubuntu 14.04 (trusty) which has libhdf5 1.8.11
Ubuntu 14.10 (utopic) has libhdf 1.8.12

See [here](http://packages.ubuntu.com/search?keywords=libhdf5-7)

**Comment by caryan** [comment]
Seems like disabling version checks could get us in trouble in the future but there can't be that much of a difference between 1.8.12 and 1.8.13.  I'll add a note to the doc this.  

I forgot about your other fix/#27 branch.  I'll merge mine into yours.

**Comment by bcdonovan** [comment]
The "right" thing to do would be to get the libhdf5 [release](https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.12/) which matches the Matlab version and build against that. That might be more simple than trying to track libhdf5 versions across linux distros.

We may now have a bit of a maintenance to do with each new Matlab release:
 * Update GCC version support
 * Update libdf5 version

**Comment by caryan** [comment]
We could also go back to static linking against the HDF5 library.

**Comment by caryan** [comment]
The __int64 trick was a hack we picked up somewhere but the correct thing to do is just include ``stdint`` in the C compatible part and it works on WIndows and Linux. Commit 6f766c8c83d9fc15bc5f7d37718e8b00ae6a0f0c solves this I think.

**Comment by caryan** [comment]
@bcdonovan for the libhdf5 issue we don't ship Linux shared libraries so it's up to the user to get that right when they compile on their own machine.  I've added (d68d4b9cb4b727307c4ed2205386e84801780d9c) a note to the README for your workaround.
