### ISSUE TITLE
:art: break-up monolithic "headings.h"

### ISSUE THREAD

**Issue by caryan** [BBN-Q/libaps2#46]

**Comment by blakejohnson** [comment]
Why?

**Comment by caryan** [comment]
Mainly style.  Sort of like not liking an `from Foo import *` in Python.  I didn't like this include everything under the kitchen sink "headings.h" because it's not clear what each compilation unit actually needs. It also makes it difficult to transfer code to any other project unless you also carry along the "headings.h"
