### ISSUE TITLE
Julia and Python wrappers `get_trigger_interval` broken

### ISSUE THREAD

**Issue by caryan** [BBN-Q/libaps2#59]

**Comment by grahamrow** [comment]
Seems like I can't get this to work in the straight C API either (on Mac, returns "inf"), despite it running fine in matlab (on Windows).

**Comment by caryan** [comment]
Hmmm, I was testing on Linux. In some limited testing I did it was reading the correct value from the hardware register.

**Comment by caryan** [comment]
Closed in 5e7bc570bcde67fe57e33929d37b54c093cf198a
