### ISSUE TITLE
Three issues on APS2 (jitter, synchronization, mutiple trigger)

### ISSUE THREAD

**Issue by jaseung** [BBN-Q/libaps2#90]
Hello, 

I have three issues to address regarding APS2. Let me explain them below. 

1.I found out that there is quite large jitter (~3 ns) on the channels and markers on each APS2 slice when it is triggered externally. On the attached video, you can see all three colors other than yellow(topmost) show ~3ns jitters. From the top to bottom are shown the markers from slice 1, slice2, slice3, and slice4 (each one used for readout1, qubit1, readout2, and qubit2, in the same order). I am using slice 1 as a master internally triggered, and one of the marker as a slave trigger. The slave trigger is cascaded to slice 2, 3 and 4 using SMA Tee. I see that the channels and markers from a single slice are in sync even though they have all same jitters with respect to Trigger Input. I don't think this jitter is normal as according to the specification for APS2, the time jitter should be less than 10 pico-second range.

I did two extra tests. One is to adjust the power level of Ref In to APS2 in case time base might not be in sync, and it didn't solve jitter. The second test was to actually trigger only one APS2 slice using an external trigger source (AFG 3022B) and to see the channel and marker output. Still  there are jitters. It really seems that Trigger Input on the slice is not really in sync with the channels and markers somehow....

Do you guys also have this jitter on APS2 (I imagine not)? Can you help us solve this issue?

2.The second issue is that the four markers(of course, and channels) from four APS2 slices are not synchronized  aside from the cable delays of trigger inputs. I brought up this issue a while ago, and so far I've been temporarily adjusting delays to physical channels to get all slices time-aligned. Please see the picture attached. It is the snapshot of markers from RabiAmp measurement with ZERO delays on physical channels. Again, from the top to bottom are shown readout marker from slice 1, qubit marker from slice2, readout marker from slice3 and qubit marker from slice4. The slice 1 is a master. The first problem is the readout marker from slice1(yellow)  comes even earlier than qubit marker from slice2 (green). For this reason, I normally put 120ns delay to the physical channel of slice1. The readout and qubit markers for slice3 and 4 look ok, but the two qubit markers(green and pink) are not even aligned. I am not sure if this problem is related with the jitter problem, but something is not clearly right. Perhaps, PLL not stable?? 

Have you seen this problem in APS2 at BBN? What could cause this and how can we fix it?

3.I have one question about triggering multiple slices. How do you guys in BBN trigger them? Power splitter? APS2-TDM?
Here we've been using a chain of cables with SMA Tee at Trigger Input of each slice. The second picture show the trigger inputs to three APS2 slices measured with an oscilloscope using 50Ohm input impedance, and the signal in pink is one of the markers from slice1 for voltage level comparison. The issue with this method is that as you can see in the picture, the rising edge is not square and  also slowly(time scale ~20ns) rises only to ~0.9V. So especially, the slave trigger shorter than 27ns can not be used since the effective length of the pulse (not square but sort of triangle shape) is too short to trigger APS2.  Experimentally, I found 27ns is the shorted slave trigger which can trigger all three following slices. However, 27ns is not short enough for 20ns single qubit pulse not to have unwanted delay that Caleb found the other day (https://github.com/BBN-Q/QGL/issues/148).

One zip file and two pictures are attached below. The zip file is mp4 file showing jitters.

Video (for issue 1):
[jitter_APS2.zip](https://github.com/BBN-Q/libaps2/files/1908697/jitter_APS2.zip)

Pictures (for issues 2 and 3):
![zerodelaysetting_aps2](https://user-images.githubusercontent.com/22563147/38754330-5d0e9aa6-3f2f-11e8-9fec-48c023260174.jpg)
![triggerinputfromslavetrigger](https://user-images.githubusercontent.com/22563147/38754335-5fee8d94-3f2f-11e8-9017-0928016b88c2.jpg)

I will appreciate your help.

**Comment by dieris** [comment]
I must say I haven't measured jitter between APS2 slices in a while. With those pulse shapes you're observing, I'm not surprised though. There are a couple of ways you can improve that:
1) If you use an APS2 slice as master, amplify your slave trigger before distributing it to other slices. Usually we don't split a marker more than twice without amplifying
2) Use the TDM as master and trigger the APS2 through the SATA cables. To do that, you need to create a TDM instrument and set its trigger as internal, while the APS2 triggers should be set as system. Make sure you have a recent (>=0.11) TDM firmware for that.

**Comment by jaseung** [comment]
Thanks for the suggestions. While the first method looks simpler, I would try to set up TDM to work soon. As far as I know, we haven't installed the basic firmware in our TDM.  Should following the instructions in APS2-TDM github be enough to set up the firmware or do you have any more detailed or specific instructions that I have to stick to?

I really wouldn't worry about the trigger thing I described since I know how to solve it now. However, as for the jitter and timing issues, I have no idea what I could do on our side. Simply triggering one APS2 slice shows that there's jitter on channel and marker with respect to the TRIG Input. Any idea what's wrong?

**Comment by jaseung** [comment]
I have one question in setting up APS-TDM basic firmware following the documentation here  https://github.com/BBN-Q/APS2-TDM.

The doc says that I must obtain a license from ComBlock. Does it mean that I need to purchase COM-5402SOFT ($750, https://comblock.com/product_list.html) to get ComBlock 5402 files (and others)? I just want to make sure everything is right.

**Comment by jaseung** [comment]
I am closing this issue as all three issues disappeared since I started to use the TDM.
