### ISSUE TITLE
Single qubit RB pulse sequence issue with APS2

### ISSUE THREAD

**Issue by jaseung** [BBN-Q/libaps2#91]
I found that the long RB pulse sequences from APS2 have problems. Basically, the physical channel(I and Q) and gate marker go out of sync as you can see below. Some extra gaps seem to be added to I/Q channels. However, if the gate marker is disabled, then the I channel looks OK on the scope. This issue can be seen only on the scope, not in the jupyter notebook, i.e. the I/Q channel and gate marker look normal in the notebook. Also, this issue seems to exist only with APS2, not APS1(I haven't seen this issue yet when using APS1). I used (Auspex) QGL in master branch for test.

In the screenshot, I am using 200 Clifford gate with 50ns qubit pulse.
* Example pictures that show abnormal qubit pulse train in RB
![clifford200_1repeat_abnormalpulses](https://user-images.githubusercontent.com/22563147/39211717-84bc71dc-47da-11e8-8a4e-4d7bfc6da190.jpg)
![clifford200_1repeat_abnormalpulses_zoomin](https://user-images.githubusercontent.com/22563147/39211689-703029de-47da-11e8-8e66-9a98548f06ce.jpg)

**Comment by matthewware** [comment]
Off hand I'd say if the the pulse plotter and the output from the APS2 are different it's probably an APS2 issue.  The pulse plotter is just taking waveform data out of the h5 files and plotting it.  If things look right in the pulse plotter and wrong on the APS2 output, it's probably a hardware issue.  I noticed on some earlier plots the gate and the RB pulses are on different APS units.  Is that the case here?  Are you using the system trigger or some other way of triggering slave APS2s?
