### ISSUE TITLE
APS2 analog channel output  amplitude changes as phase skew does.

### ISSUE THREAD

**Issue by jaseung** [BBN-Q/libaps2#94]
I noticed that the amplitude of analog output varies as a function of phase skew. As I change the phase skew from 0 to 360 degree, the amplitude oscillate, hitting the max of about 1V at 90 and 270 degree. At those 90 and 270 points, the waveform goes crazy, not sinusoidal any more. I found this by watching the continuous waveforms on the scope while running the mixer optimization. I verified the same thing using continuous mode of the APS2.  I tried different frequencies(25, 50, 100)  and the results are the same.

This might not affect any measurement since we normally set the phase skew during mixer optimization and don't change the value. However, the change of amplitude vs phase skew makes setting the channel scale a bit meaningless and concerning.

I am using the firmware ver 4.7 on our APS2.

I attached a mp4 which shows the chan1 and chan2 while the phase skew varies from 0 to 360.
[phaseSkewScan.zip](https://github.com/BBN-Q/libaps2/files/2288353/phaseSkewScan.zip)

**Comment by matthewware** [comment]
Hi Jaseung,

The APS2 uses a correction matrix to correct for phase and amplitude imbalance in both arms.  I'll have time to write out a more detailed response tomorrow morning, but basically a phase imbalance will lead to amplitude error in the RF output.  So the correction matrix looks like:

[i_scale, 0;0, q_scale] * [amp, amp*tan(phi); 0, 1/cos(phi)]

for *_scale offsets and phi phase skews.  See https://github.com/BBN-Q/libaps2/blob/371283fcfdc31f6511a94c71e2bd292cdd19a03c/src/lib/APS2.cpp#L541-L568

There's a short write up here: https://wiki.analog.com/resources/eval/user-guides/ad-fmcomms1-ebz/iq_correction

Obviously this matrix is undefined for phi values of pi/2 and 3*pi/2.  As you pointed out, we usually set the mixer cal parameters once and only change them on recalibration.  So all amplitude values after the calibration are scaled appropriately.

**Comment by jaseung** [comment]
Hi Matt, 

Thanks for the comment. I didn't know that the correction matrix is applied to the analog outputs of the APS2; I thought _set_mixer_phase_skew_ and _set_mixer_amplitude_imbalance_ just change the phase offset of either I or Q and the ratio of I and Q amplitude, respectively. Now everything I observed on the scope makes sense.

**Comment by matthewware** [comment]
Hi Jasenug,

No worries.  I can see how that might worry someone just looking at it on the scope!  In practical situations IQ mixers will have 0-20 deg of skew so we would hope to typically be pretty far away from the 90 and 270 degree points.

**Comment by matthewware** [comment]
If things are good on your end I'll close this issue for now.
